language: python
python:
  - "2.7"
script: nosetests xivo_stat
notifications:
  email:
    recipients:
      - dev.wazo+tests-reports@gmail.com
    on_success: change
    on_failure: change
branches:
  only:
    - master
sudo: false
