# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/wazo-stat/conf.d/

log_filename: /var/log/xivo-stat.log
debug: false

# Database connection informations.
db_uri: postgresql://asterisk:proformatique@localhost/asterisk?application_name=wazo-stat
