# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/wazo-stat/conf.d/

log_filename: /var/log/wazo-stat.log
debug: false

# Database connection informations.
db_uri: postgresql://asterisk:proformatique@localhost/asterisk?application_name=wazo-stat

# Connection info to the authentication server
auth:
  host: localhost
  port: 9497
  prefix: null
  https: false

# Confd connection information
confd:
  host: localhost
  port: 9486
  prefix: null
  https: false
